title:            Clackity Clack
description:      Hopefully making the clackity noise.
url:              https://clackity.io

links:
  - name:         About
    url:          /about
  - name:         Twitter
    url:          https://twitter.com/mikewest
  - name:         GitHub
    url:          https://github.com/mikewest

highlighter:      pygments
permalink:        pretty
markdown:         kramdown
gems:
  - jekyll-feed
